CREATE TABLE IF NOT EXISTS `zrp_players` (
  `citizenid` VARCHAR(50) NOT NULL,
  `xp` INT NOT NULL DEFAULT 0,
  `level` INT NOT NULL DEFAULT 1,
  `rep` INT NOT NULL DEFAULT 0,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`citizenid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `zrp_hideout` (
  `citizenid` VARCHAR(50) NOT NULL,
  `stash_level` INT NOT NULL DEFAULT 1,
  `craft_level` INT NOT NULL DEFAULT 1,
  `medical_level` INT NOT NULL DEFAULT 1,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`citizenid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `zrp_skills` (
  `citizenid` VARCHAR(50) NOT NULL,
  `points` INT NOT NULL DEFAULT 0,
  `trees` LONGTEXT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`citizenid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `zrp_characters` (
  `citizenid` VARCHAR(50) NOT NULL,
  `license` VARCHAR(64) NOT NULL,
  `display_name` VARCHAR(128) NOT NULL,
  `appearance` LONGTEXT NULL,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`citizenid`),
  KEY `idx_zrp_characters_license` (`license`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
